docker:
  image: "openjdk:8-jdk"

env:
  MAVEN_OPTS: "-XX:MaxPermSize=256m -Xmx1g"

merge:
  commanders:
    - aistomin
  script: |-
    find / -type d -name "openjdk" 2>/dev/null
    echo $JAVA_HOME
    export JAVA_HOME=$(readlink -ze $(which java) | xargs -0 dirname | xargs -0 dirname)
    export PATH="${JAVA_HOME}/bin:${PATH}"
    echo $JAVA_HOME
    mvn -version
    mvn clean install package javadoc:javadoc
