env:
  MAVEN_OPTS: "-XX:MaxPermSize=256m -Xmx1g"

merge:
  commanders:
    - aistomin
  script: |-
    echo which java
    java -version
    mvn -version
    mvn clean install package javadoc:javadoc
