docker:
  image: "maven:3.6.3-openjdk-8"

env:
  MAVEN_OPTS: "-XX:MaxPermSize=256m -Xmx1g"

merge:
  commanders:
    - aistomin
  script: |-
    export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
    export PATH=$JAVA_HOME/bin:$PATH
    echo $JAVA_HOME
    mvn -version
    mvn clean install package javadoc:javadoc
