env:
  MAVEN_OPTS: "-XX:MaxPermSize=256m -Xmx1g"

merge:
  commanders:
    - aistomin
  script: |-
    export JAVA_HOME=$(readlink -ze $(which java) | xargs -0 dirname | xargs -0 dirname)
    export PATH=$PATH:$JAVA_HOME/bin
    java -version
    mvn -version
    mvn clean install package javadoc:javadoc
