env:
  MAVEN_OPTS: "-XX:MaxPermSize=256m -Xmx1g"

merge:
  commanders:
    - aistomin
  script: |-
    export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64/jre"
    export PATH=$PATH:$JAVA_HOME/bin
    java -version
    mvn -version
    mvn clean install package javadoc:javadoc
