docker:
  image: "maven:3.6.3-openjdk-8"

env:
  MAVEN_OPTS: "-XX:MaxPermSize=256m -Xmx1g"

merge:
  commanders:
    - aistomin
  script: |-
    ENV JAVA_HOME=/usr/lib/jvm/default-jvm
    ENV PATH="${JAVA_HOME}/bin:${PATH}"
    echo $JAVA_HOME
    mvn -version
    mvn clean install package javadoc:javadoc
