docker:
  image: "maven:3.6.3-openjdk-8"

env:
  MAVEN_OPTS: "-XX:MaxPermSize=256m -Xmx1g"

merge:
  commanders:
    - aistomin
  script: |-
    echo $JAVA_HOME
    mvn -version
    mvn clean install package javadoc:javadoc
